//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddtoCart
    {
        public int id { get; set; }
        public Nullable<int> cartbday { get; set; }
        public Nullable<int> cartbaby { get; set; }
        public Nullable<int> cartbachelor { get; set; }
        public Nullable<int> cartwedding { get; set; }
        public Nullable<int> cartanni { get; set; }
        public Nullable<int> cartreunion { get; set; }
        public Nullable<int> cartcocktail { get; set; }
    
        public virtual birthdaytable birthdaytable { get; set; }
        public virtual Reunion Reunion { get; set; }
        public virtual Anniversary Anniversary { get; set; }
        public virtual babyshowertable babyshowertable { get; set; }
        public virtual BachelorParty BachelorParty { get; set; }
        public virtual CocktailParty CocktailParty { get; set; }
        public virtual Wedding Wedding { get; set; }
    }
}
