//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BachelorParty
    {
        public int id { get; set; }
        public Nullable<int> bacheloruserid { get; set; }
        public Nullable<int> bachelorid { get; set; }
        public Nullable<int> bachelordecorations { get; set; }
        public Nullable<int> bachelortheme { get; set; }


        [Required(ErrorMessage = "Choose  chairs")]
        [Range(0, 500, ErrorMessage = "The number of chairs must be between 0 and 500.")]
        public Nullable<int> bachelorchairs { get; set; }



        [Required(ErrorMessage = "Choose  Tables")]
        [Range(0, 500, ErrorMessage = "The number of Tables must be between 0 and 100.")]
        public Nullable<int> bachelortables { get; set; }
        public Nullable<int> bachelorhallcapacity { get; set; }


        [Required(ErrorMessage = "DateTime is Required")]

        public Nullable<System.DateTime> bachelordatetime { get; set; }
        public Nullable<int> bachelorcakes { get; set; }
        public Nullable<int> bachelorlocation { get; set; }
        public Nullable<long> bacheloreventcost { get; set; }
        public bool bachelorbeverages { get; set; }
    
        public virtual Usertable Usertable { get; set; }
        public virtual EventName EventName { get; set; }
        public virtual decorationtable decorationtable { get; set; }
        public virtual themetable themetable { get; set; }
        public virtual caketable caketable { get; set; }
        public virtual locationtable locationtable { get; set; }
    }
}
