//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class birthdaytable
    {
        public int id { get; set; }
        public Nullable<int> bdayuserid { get; set; }
        public Nullable<int> bdayid { get; set; }
        public Nullable<int> bdaydecorations { get; set; }
        public Nullable<int> bdaytheme { get; set; }


        [Required(ErrorMessage = "Choose  chairs")]
        [Range(0, 500, ErrorMessage = "The number of chairs must be between 0 and 500.")]
        public Nullable<int> bdaychairs { get; set; }


        [Required(ErrorMessage = "Choose  Tables")]
        [Range(0, 500, ErrorMessage = "The number of Tables must be between 0 and 100.")]
        public Nullable<int> bdaytables { get; set; }
        public Nullable<int> bdayhallcapacity { get; set; }


        [Required(ErrorMessage = "DateTime is Required")]

        public Nullable<System.DateTime> bdaydatetime { get; set; }
        public Nullable<int> bdaycakes { get; set; }
        public Nullable<int> bdaylocation { get; set; }
        public Nullable<long> bdayeventcost { get; set; }
        public bool bdaybeverages { get; set; }
    
        public virtual caketable caketable { get; set; }
        public virtual decorationtable decorationtable { get; set; }
        public virtual EventName EventName { get; set; }
        public virtual locationtable locationtable { get; set; }
        public virtual themetable themetable { get; set; }
        public virtual Usertable Usertable { get; set; }
    }
}
