//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CocktailParty
    {
        public int id { get; set; }
        public Nullable<int> cockuserid { get; set; }
        public Nullable<int> cockid { get; set; }
        public Nullable<int> cockdecorations { get; set; }
        public Nullable<int> cocktheme { get; set; }


        [Required(ErrorMessage = "Choose  chairs")]
        [Range(0, 500, ErrorMessage = "The number of chairs must be between 0 and 500.")]
        public Nullable<int> cockchairs { get; set; }


        [Required(ErrorMessage = "Choose  Tables")]
        [Range(0, 500, ErrorMessage = "The number of Tables must be between 0 and 100.")]
        public Nullable<int> cocktables { get; set; }
        public Nullable<int> cockhallcapacity { get; set; }


        [Required(ErrorMessage = "DateTime is Required")]

        public Nullable<System.DateTime> cockdatetime { get; set; }
        public Nullable<int> cockcakes { get; set; }
        public Nullable<int> cocklocation { get; set; }
        public Nullable<long> cockeventcost { get; set; }
        public bool cockbeverages { get; set; }
    
        public virtual caketable caketable { get; set; }
        public virtual decorationtable decorationtable { get; set; }
        public virtual EventName EventName { get; set; }
        public virtual locationtable locationtable { get; set; }
        public virtual themetable themetable { get; set; }
        public virtual Usertable Usertable { get; set; }
    }
}
