//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class datetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datetable()
        {
            this.eventnames = new HashSet<eventname>();
        }

        [Required]
        public int dateid { get; set; }

        [Required(ErrorMessage = "datesavailable is required.")]
        [DataType(DataType.Date, ErrorMessage = "Invalid datetime format for datesavailable.")]
        public Nullable<System.DateTime> datesavailable { get; set; }

        [Required(ErrorMessage = "IsDeleteddate is required.")]
        [Range(typeof(bool), "true", "false", ErrorMessage = "IsDeleteddate must be a boolean value.")]
        public bool IsDeleteddate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventname> eventnames { get; set; }
    }
}
