//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventname
    {
        public Nullable<int> eventid { get; set; }
        public Nullable<int> eventdate { get; set; }
        public Nullable<int> eventtime { get; set; }
        public Nullable<long> eventhallcapacity { get; set; }
        public bool eventcatering { get; set; }
        public Nullable<int> eventlocation { get; set; }
        public Nullable<int> eventtheme { get; set; }
        public Nullable<long> eventcost { get; set; }
        public int eventnameid { get; set; }
    
        public virtual datetable datetable { get; set; }
        public virtual eventstable eventstable { get; set; }
        public virtual timetable timetable { get; set; }
        public virtual locationtable locationtable { get; set; }
        public virtual themetable themetable { get; set; }
    }
}
