//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventManagement2Entities2 : DbContext
    {
        public EventManagement2Entities2()
            : base("name=EventManagement2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caketable> caketables { get; set; }
        public virtual DbSet<decorationtable> decorationtables { get; set; }
        public virtual DbSet<EventName> EventNames { get; set; }
        public virtual DbSet<locationtable> locationtables { get; set; }
        public virtual DbSet<Roletable> Roletables { get; set; }
        public virtual DbSet<themetable> themetables { get; set; }
        public virtual DbSet<Usertable> Usertables { get; set; }
        public virtual DbSet<birthdaytable> birthdaytables { get; set; }
        public virtual DbSet<Reunion> Reunions { get; set; }
        public virtual DbSet<Anniversary> Anniversaries { get; set; }
        public virtual DbSet<babyshowertable> babyshowertables { get; set; }
        public virtual DbSet<BachelorParty> BachelorParties { get; set; }
        public virtual DbSet<CocktailParty> CocktailParties { get; set; }
        public virtual DbSet<Wedding> Weddings { get; set; }
        public virtual DbSet<feedbacktable> feedbacktables { get; set; }
        public virtual DbSet<FinalPaymentReceived> FinalPaymentReceiveds { get; set; }
    
        public virtual ObjectResult<Validate_User_Result> Validate_User(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Validate_User_Result>("Validate_User", usernameParameter, passwordParameter);
        }
    }
}
