//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalPaymentReceived
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string username { get; set; }
        public string usercontact { get; set; }
        public string usermail { get; set; }
        public string razorpayid { get; set; }
        public Nullable<System.DateTime> bookingdatetime { get; set; }
        public Nullable<System.DateTime> paymentdatetime { get; set; }
        public Nullable<int> totalcost { get; set; }
        public Nullable<int> partialamount { get; set; }
        public Nullable<int> eventid { get; set; }
        public bool ispaid { get; set; }
    
        public virtual Usertable Usertable { get; set; }
    }
}
