//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class locationtable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public locationtable()
        {
            this.eventnames = new HashSet<eventname>();
        }

        [Required(ErrorMessage = "locationid is required.")]
        public int locationid { get; set; }


        [Required(ErrorMessage = "locationname is required.")]
        public string locationname { get; set; }

        [Required]
        public Nullable<long> pincode { get; set; }


        [Required(ErrorMessage = "IsDeletedlocation is required.")]
        public bool IsDeletedlocation { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventname> eventnames { get; set; }
    }
}
