//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reunion
    {
        public int id { get; set; }
        public Nullable<int> reunionuserid { get; set; }
        public Nullable<int> reunionid { get; set; }
        public Nullable<int> reuniondecorations { get; set; }
        public Nullable<int> reuniontheme { get; set; }
        public Nullable<int> reunionchairs { get; set; }
        public Nullable<int> reuniontables { get; set; }
        public Nullable<int> reunionhallcapacity { get; set; }
        public Nullable<System.DateTime> reuniondatetime { get; set; }
        public Nullable<int> reunioncakes { get; set; }
        public Nullable<int> reunionlocation { get; set; }
        public Nullable<long> reunioneventcost { get; set; }
        public bool reunionbeverages { get; set; }
        public bool reunionPhotography { get; set; }
        public bool reunionStyling { get; set; }
        public bool reunionHospitality { get; set; }
    
        public virtual caketable caketable { get; set; }
        public virtual decorationtable decorationtable { get; set; }
        public virtual EventName EventName { get; set; }
        public virtual locationtable locationtable { get; set; }
        public virtual Usertable Usertable { get; set; }
        public virtual themetable themetable { get; set; }
    }
}
