//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class timetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timetable()
        {
            this.eventnames = new HashSet<eventname>();
        }


        [Required(ErrorMessage ="timeid is required.")]
        public int timeid { get; set; }

        [Required(ErrorMessage = "time is required.")]
        public Nullable<System.TimeSpan> timesavailable { get; set; }

        [Required(ErrorMessage = "IsDeletedTime is required.")]
        public bool IsDeletedtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventname> eventnames { get; set; }
    }
}
