//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.eventnames = new HashSet<eventname>();
        }
    
        public int TUserid { get; set; }
        public string TUsername { get; set; }
        public string TPassword { get; set; }
        public string TEmail { get; set; }
        public Nullable<long> TMobile { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> TRoleid { get; set; }
        public byte[] Tprofile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventname> eventnames { get; set; }
        public virtual RoleTable RoleTable { get; set; }
    }
}
