//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wedding
    {
        public int id { get; set; }
        public Nullable<int> weddinguserid { get; set; }
        public Nullable<int> weddingid { get; set; }
        public Nullable<int> weddingdecorations { get; set; }
        public Nullable<int> weddingtheme { get; set; }


        [Required(ErrorMessage = "Choose  chairs")]
        [Range(0, 500, ErrorMessage = "The number of chairs must be between 0 and 500.")]
        public Nullable<int> weddingchairs { get; set; }


        [Required(ErrorMessage = "Choose  Tables")]
        [Range(0, 500, ErrorMessage = "The number of Tables must be between 0 and 100.")]
        public Nullable<int> weddingtables { get; set; }
        public Nullable<int> weddinghallcapacity { get; set; }


        [Required(ErrorMessage = "DateTime is Required")]

        public Nullable<System.DateTime> weddingdatetime { get; set; }
        public Nullable<int> weddingcakes { get; set; }
        public Nullable<int> weddinglocation { get; set; }
        public Nullable<long> weddingeventcost { get; set; }
        public bool weddingbeverages { get; set; }
        public bool weddingPhotography { get; set; }
        public bool weddingStyling { get; set; }
        public bool weddingHospitality { get; set; }
    
        public virtual caketable caketable { get; set; }
        public virtual decorationtable decorationtable { get; set; }
        public virtual EventName EventName { get; set; }
        public virtual locationtable locationtable { get; set; }
        public virtual themetable themetable { get; set; }
        public virtual Usertable Usertable { get; set; }
    }
}
